### PR TITLE
Set up database APIs

### PR DESCRIPTION
**Pull request by adelefelicia**
- Created django project (server_comm)
- Added support for postgres database
- Created app for managing data in database (data_manager)
- Added models in data manger for database
- Implemented API to access and manage data

The code I wrote (that is not auto-generated) and should be reviewed can be found in:
- data_manager: models.py, serializers.py, views.py, urls.py, admin.py
- server_comm: settings.py, urls.py

### CODE REVIEW

**Comment by EliHaugu** [comment]
Ran on my PC, every bit of the tutorial worked :D Would add pycache stuff to .gitignore

**Comment by EliHaugu** [comment]
The pipeline is failing to build as it has no requirements.txt file to build from

**Comment by EliHaugu** [comment]
I'll merge main into this branch

**Comment by adelefelicia** [comment]
The black and isort formatting rules were not compatible with flake8, so I added a pyproject.toml file that configures them to be compatible

**Review by haakon98 — APPROVED** [review]

**Pull request merged**
