### PR TITLE
Make fields nullable + enforce correct keys for comm/conn ids

### PR DESCRIPTION
**Pull request by adelefelicia**
- Make x_pos and y_pos nullable in database (was previously only made optional for the API)
- Make comm/conn ids optional for API and nullable in database
- Make "{}" a valid value for comm/conn ids
- Validate that comm/conn ids keys are one of the specified mappings (previously allowed any as long as the required ids were also included)
- Make comm protocols optional for categories
- Test runner returns node ID instead of node label for results when running flows

### CODE REVIEW

**Comment by EliHaugu** [comment]
While we're changing the models, is the intended behavior that you should not be able to make a category without adding a communication protocol? Does a device need to be either WIFI, BLE, LTE? Do we use this anywhere or is it not necessary to enforce this?

**Comment by EliHaugu** [comment]
* Tested creating node with x_pos y_pos None, worked
* I could not make a device without a comm protocol is this intended?
* Tested creating a bluetooth category, then got error when device did not have mac, so working as intended

**Comment by adelefelicia** [comment]
Probably not necessary to enforce comm protocols for categories. Will change the models to accommodate this

**Comment by adelefelicia** [comment]
Added these by request to clean up the models a bit:
- Make comm protocols optional for categories
- Test runner returns node ID instead of node label for results when running flows

**Review by haakon98 — APPROVED** [review]

**Pull request merged**
